### PR TITLE
minimal set of fixes to get tests passing in julia 0.5

### PR DESCRIPTION
**Pull request by Cody-G**
Requires https://github.com/lindahua/EmpiricalRisks.jl/pull/19

### CODE REVIEW

**Comment by merl-dev** [comment]
The package will pass all tests with a more minimalist set of changes:

1. delete dependence on `ArrayViews` (in Regression.jl **line 4**)
2. replace **line 15** in src/common.jl with `fill!(view(Xa, m+1,  :), v)`
3. keep your bug fix in test/linearreg.jl **line 13** 

As per the `ArrayViews` README: 

> By and large, this package is no longer necessary: base julia now has efficient SubArrays (i.e., sub and slice)

**Comment by Cody-G** [comment]
@merl-dev you are totally right, see my new PR #19

**Comment by merl-dev** [comment]
To get it through Travis you may want to remove the "nightly" from the travis file. 

You can also remove ArrayViews from REQUIRE.  

I also have a branch EmpriricalRisks/rem_arrayviews that also replaces ArrayViews.

(I've only made these updates locally as I plow through the package history for doing this kind of work.  You might want to consider upgrading to newer, maintained packages)

**Comment by Cody-G** [comment]
Okay thanks for the info.  By the way, do you have a favorite replacement
package for high-performance L1-regularized linear regression?  Thanks!

**Comment by merl-dev** [comment]
No but you can look at GLMNet, of which there are 2 versions, fortran based and pure Julia, Lasso.jl ... you could also look into the tool kits provided through JuliaML, JuMP ... where there is a ton of active development.

**Pull request closed without merging**
